### ISSUE TITLE
Can not conform URLRequestConfigurable Swift 3.0.1 - Alamofire 4.0.1

### ISSUE THREAD

**Issue by methebao** [gmarm/AlamofireURLRequestConfigurable#2]
I can not conform URLRequestConfigurable to Router enum. Also I have got that in Alamofire 4.0.1 which don't have URLRequestConfigurable protocol.

I'm new in Alamofire and sorry if my question is so stupid :D

**Comment by gmarm** [comment]
No problem, have you checked the example included?

**Comment by methebao** [comment]
OK , I solved this issues
This tool is very useful.
Thank you.
